### PR TITLE
fix compiling errors by using newest nana

### PR DESCRIPTION
**Pull request by k1988**

### CODE REVIEW

**Comment by qPCR4vir** [comment]
Wow!
@k1988 (Terry ?) Thank you very much for your effort and your interest.
It is my fault. I need at least to document this things.
But first a question: It is now just compiling or it is also running? If so, please post an screen shot! I have never seen it working.
This is the (short) history: nana uses in Windows a native FileOpen/Save etc. common dialog. To be portable, @cnjinhao wrote from scratch using "only" nana a version for Linux. I wanted to contribute, but being in Windows, I had no access to that code. So, I took that "Linux" code and eliminated all the direct Linux dependence's trying to make it truly portable (that is the point of using nana, Ok?). I wanted it to be an option: you use the native or the nana dialog, at your wish. But first I wanted to make it available as one more example, so I adapted it to be a self contained example of file explorer. In that way I also introduced much of my own style of using nana (how can I write with another style?) and also I used the filesystem that come with VS / and / or the adaptation of the nana::filesystem to implement the std::filesystem... I think you had reverted some of that. No problem - it   is Ok. The important thing is to have a first working version.
But a have never ended that small project... it was half a way from that.
I will figure out how to merge, create two versions or just a new branch...

**Comment by qPCR4vir** [comment]
BTW, have you compiled all the other examples? If yes it will be good to documented that.
What was the exact commit you used to compile the nana library you used here?
Thank again.

**Comment by k1988** [comment]
i has compiled and tested all the other examples with last commit of nana：https://github.com/cnjinhao/nana/commit/faa74047db36da7c04b36380dd6933ed1ca16b3d

other examples run perfect!

**Comment by qPCR4vir** [comment]
Hi,
I merged your two commits, and it works now. Thank !
file_explorer

**Pull request merged**
